/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-04-09 16:53:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SolicitarViajeView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/D:/Dropbox/ISST/Trabajo/ISST-Grupo10-Trip/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip/WEB-INF/lib/shiro-web-1.4.0.jar!/META-INF/shiro.tld", Long.valueOf(1494006348000L));
    _jspx_dependants.put("jar:file:/D:/Dropbox/ISST/Trabajo/ISST-Grupo10-Trip/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/WEB-INF/lib/shiro-web-1.4.0.jar", Long.valueOf(1554125764558L));
    _jspx_dependants.put("/css/login.min.css", Long.valueOf(1554203401000L));
    _jspx_dependants.put("/css/style.min.css", Long.valueOf(1554203401000L));
    _jspx_dependants.put("/css/style.css", Long.valueOf(1554207313000L));
    _jspx_dependants.put("jar:file:/D:/Dropbox/ISST/Trabajo/ISST-Grupo10-Trip/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Trip/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098703890000L));
    _jspx_dependants.put("/css/login.css", Long.valueOf(1554822300356L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1554125775544L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("<title>Trip-Solicitar</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Custom fonts for this template -->\r\n");
      out.write("<link href=\"vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"vendor/simple-line-icons/css/simple-line-icons.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("<style>");
      out.write("/*!\r\n");
      out.write(" * Start Bootstrap - Landing Page v5.0.3 (https://startbootstrap.com/template-overviews/landing-page)\r\n");
      out.write(" * Copyright 2013-2019 Start Bootstrap\r\n");
      out.write(" * Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap-landing-page/blob/master/LICENSE)\r\n");
      out.write(" */body{font-family:Lato,'Helvetica Neue',Helvetica,Arial,sans-serif}h1,h2,h3,h4,h5,h6{font-family:Lato,'Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:700}header.masthead{position:relative;background-color:#343a40;background:url(../img/bg-masthead.jpg) no-repeat center center;background-size:cover;padding-top:8rem;padding-bottom:8rem}header.masthead .overlay{position:absolute;background-color:#212529;height:100%;width:100%;top:0;left:0;opacity:.3}header.masthead h1{font-size:2rem}@media (min-width:768px){header.masthead{padding-top:12rem;padding-bottom:12rem}header.masthead h1{font-size:3rem}}.showcase .showcase-text{padding:3rem}.showcase .showcase-img{min-height:30rem;background-size:cover}@media (min-width:768px){.showcase .showcase-text{padding:7rem}}.features-icons{padding-top:7rem;padding-bottom:7rem}.features-icons .features-icons-item{max-width:20rem}.features-icons .features-icons-item .features-icons-icon{height:7rem}.features-icons .features-icons-item .features-icons-icon i{font-size:4.5rem}.features-icons .features-icons-item:hover .features-icons-icon i{font-size:5rem}.testimonials{padding-top:7rem;padding-bottom:7rem}.testimonials .testimonial-item{max-width:18rem}.testimonials .testimonial-item img{max-width:12rem;-webkit-box-shadow:0 5px 5px 0 #adb5bd;box-shadow:0 5px 5px 0 #adb5bd}.call-to-action{position:relative;background-color:#343a40;background:url(../img/bg-masthead.jpg) no-repeat center center;background-size:cover;padding-top:7rem;padding-bottom:7rem}.call-to-action .overlay{position:absolute;background-color:#212529;height:100%;width:100%;top:0;left:0;opacity:.3}footer.footer{padding-top:4rem;padding-bottom:4rem}");
      out.write("</style>\r\n");
      out.write("<style>");
      out.write("body {\r\n");
      out.write("    font-family: \"Lato\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-color: #000;\r\n");
      out.write("    background-image: url(\"/img/avion.jpg\");\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media  (max-width: 768px) {\r\n");
      out.write("\r\n");
      out.write("    .sidenav {\r\n");
      out.write("        background-size: 100% auto;\r\n");
      out.write("        padding-top: 5vh;\r\n");
      out.write("    }\r\n");
      out.write("    .login-form{\r\n");
      out.write("        margin-top: 40vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .register-form{\r\n");
      out.write("        margin-top: 30vh;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 768px){\r\n");
      out.write("\r\n");
      out.write("    .sidenav {\r\n");
      out.write("        background-size: auto 100%;\r\n");
      out.write("        padding-top: 5vh;\r\n");
      out.write("        width: 45vw;\r\n");
      out.write("        position: fixed;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    .main{\r\n");
      out.write("        margin-left: 50vw\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".form-group{\r\n");
      out.write("    margin-bottom:2vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".login-main-text{\r\n");
      out.write("    color: #111;\r\n");
      out.write("    padding-top: 30vh;\r\n");
      out.write("    padding-bottom: 5vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title-text{\r\n");
      out.write("    color: #fefefe;\r\n");
      out.write("    padding: 10vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-black{\r\n");
      out.write("    background-color: #000;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}");
      out.write("</style>\r\n");
      out.write("<style>");
      out.write("/*!\r\n");
      out.write(" * Start Bootstrap - Landing Page v5.0.3 (https://startbootstrap.com/template-overviews/landing-page)\r\n");
      out.write(" * Copyright 2013-2019 Start Bootstrap\r\n");
      out.write(" * Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap-landing-page/blob/master/LICENSE)\r\n");
      out.write(" */body{font-family:Lato,'Helvetica Neue',Helvetica,Arial,sans-serif}h1,h2,h3,h4,h5,h6{font-family:Lato,'Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:700}header.masthead{position:relative;background-color:#343a40;background:url(../img/bg-masthead.jpg) no-repeat center center;background-size:cover;padding-top:8rem;padding-bottom:8rem}header.masthead .overlay{position:absolute;background-color:#212529;height:100%;width:100%;top:0;left:0;opacity:.3}header.masthead h1{font-size:2rem}@media (min-width:768px){header.masthead{padding-top:12rem;padding-bottom:12rem}header.masthead h1{font-size:3rem}}.showcase .showcase-text{padding:3rem}.showcase .showcase-img{min-height:30rem;background-size:cover}@media (min-width:768px){.showcase .showcase-text{padding:7rem}}.features-icons{padding-top:7rem;padding-bottom:7rem}.features-icons .features-icons-item{max-width:20rem}.features-icons .features-icons-item .features-icons-icon{height:7rem}.features-icons .features-icons-item .features-icons-icon i{font-size:4.5rem}.features-icons .features-icons-item:hover .features-icons-icon i{font-size:5rem}.testimonials{padding-top:7rem;padding-bottom:7rem}.testimonials .testimonial-item{max-width:18rem}.testimonials .testimonial-item img{max-width:12rem;-webkit-box-shadow:0 5px 5px 0 #adb5bd;box-shadow:0 5px 5px 0 #adb5bd}.call-to-action{position:relative;background-color:#343a40;background:url(../img/bg-masthead.jpg) no-repeat center center;background-size:cover;padding-top:7rem;padding-bottom:7rem}.call-to-action .overlay{position:absolute;background-color:#212529;height:100%;width:100%;top:0;left:0;opacity:.3}footer.footer{padding-top:4rem;padding-bottom:4rem}");
      out.write("</style>\r\n");
      out.write("<style>");
      out.write("/*** LIU ***/\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    font-family: \"Lato\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".datos {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    background-color: #fefefe\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".viaje{\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    background-color: #d1d1d1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listaviajes{\r\n");
      out.write("    background-color: #dddddd;\r\n");
      out.write("    padding: 40px;\r\n");
      out.write("}\r\n");
      out.write(".descripcion{\r\n");
      out.write("     padding: 40px;\r\n");
      out.write(" }\r\n");
      out.write(".notificaciones {\r\n");
      out.write("    padding: 30px;\r\n");
      out.write("    background-color: #eeeeee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media  (max-height: 768px) {\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 768px){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".requestForm{\r\n");
      out.write("    padding-top: 5em;\r\n");
      out.write("    padding-left: 20%;\r\n");
      out.write("    padding-right: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-row{\r\n");
      out.write("    padding-bottom: 4%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control{\r\n");
      out.write("    padding-top: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".IBAN {\r\n");
      out.write("  text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-aceptar{\r\n");
      out.write("    background-color: #00adb5;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/** JESUS **/\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".body{\r\n");
      out.write("    background: #6c757d;\r\n");
      out.write("    text-decoration-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".circulo{\r\n");
      out.write("    weight: 10rem;\r\n");
      out.write("    height: 10rem;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tmargin-top: 4%;\r\n");
      out.write("\tpadding: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-row .form-group-row .form-group{\r\n");
      out.write("\tmargin-top: 1%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contenedor{\r\n");
      out.write("\tpadding: 3%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-md navbar-light bg-light fixed-top\">\r\n");
      out.write("\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: #00adb5; letter-spacing: 3px\">Gestión de viajes</a>\r\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler\" type=\"bottom\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\tdata-target=\"#navbarResponsive\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Cerrar sesión</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t<div class=\"requestForm\">\r\n");
      out.write("\t\t\t<form>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1>Datos del solicitante</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-12\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">Email</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"email\" class=\"form-control\" id=\"exampleFormControlInput1\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"name@example.com\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">Nombre</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"Nombre\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">DNI/NIF</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" placeholder=\"DNI/NIF\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">Cargo</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Puesto de trabajo dentro de la empresa\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">Telefono</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Telefono fijo o móvil  \">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">IBAN</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" class=\"form-control IBAN\" placeholder=\"IBAN\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1>Datos del viaje</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlSelect1\">Tipo de viaje</label> <select\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>4</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlTextarea1\">Objeto del viaje</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("\t\t\t\t\t\t\trows=\"3\">\r\n");
      out.write("                </textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlSelect1\">Medio de transporte</label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Taxi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Avión</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Tren</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Metro</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Barco</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Bus</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <select class=\"form-control\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Taxi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Avión</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Tren</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Metro</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Barco</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Bus</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <select class=\"form-control\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>Taxi</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Avión</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Tren</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Metro</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Barco</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>Bus</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-8\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlInput1\">Datos vehículo\r\n");
      out.write("\t\t\t\t\t\t\tpersonal</label>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Matrícula\">\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Marca y modelo\">\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Titular\">\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Periodo inicio</label> <input type=\"date\" name=\"bday\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmax=\"3000-12-31\" min=\"1000-01-01\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label>Periodo fin</label> <input type=\"date\" name=\"bday\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmin=\"1000-01-01\" max=\"3000-12-31\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlTextarea1\">Objeto del viaje</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("\t\t\t\t\t\t\trows=\"3\">\r\n");
      out.write("                </textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<h1>Gastos previstos</h1>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"exampleFormControlTextarea1\">Exponga aquí los\r\n");
      out.write("\t\t\t\t\t\t\tgastos previstos del viaje</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea class=\"form-control\" id=\"exampleFormControlTextarea1\"\r\n");
      out.write("\t\t\t\t\t\t\trows=\"3\">\r\n");
      out.write("                </textarea>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"inputEmail3\" class=\"col-form-label\">Gastos\r\n");
      out.write("\t\t\t\t\t\t\tprevistos</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"number\" value=\"1000\" min=\"0\" step=\"0.01\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-number-to-fixed=\"2\" data-number-stepfactor=\"100\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control currency\" id=\"c2\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<label for=\"exampleFormControlFile1\">Adjuntar factura</label> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"file\" class=\"form-control-file\" id=\"exampleFormControlFile1\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-row\">\r\n");
      out.write("\t\t\t\t\t<span class=\"col-6\"></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"col-3 btn\" href=\"registrar.html\">Cancelar</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"col-3 btn btn-aceptar\"\r\n");
      out.write("\t\t\t\t\t\thref=\"registrar.html\">Guardar cambios</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
